"""initial_schema

Revision ID: f97baf894a06
Revises: 
Create Date: 2026-05-07 19:10:12.009224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f97baf894a06'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('match_type', sa.Enum('TEST', 'ODI', 'T20I', 'T20', name='matchtype'), nullable=False),
    sa.Column('venue', sa.String(length=128), nullable=True),
    sa.Column('ground', sa.String(length=128), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('team1', sa.String(length=64), nullable=False),
    sa.Column('team2', sa.String(length=64), nullable=False),
    sa.Column('winner', sa.String(length=64), nullable=True),
    sa.Column('toss_winner', sa.String(length=64), nullable=True),
    sa.Column('toss_decision', sa.Enum('BAT', 'BOWL', name='tossdecision'), nullable=True),
    sa.Column('result_margin', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matches'))
    )
    op.create_index(op.f('ix_matches_date'), 'matches', ['date'], unique=False)
    op.create_index(op.f('ix_matches_external_id'), 'matches', ['external_id'], unique=True)
    op.create_index(op.f('ix_matches_ground'), 'matches', ['ground'], unique=False)
    op.create_index(op.f('ix_matches_match_type'), 'matches', ['match_type'], unique=False)
    op.create_index(op.f('ix_matches_team1'), 'matches', ['team1'], unique=False)
    op.create_index(op.f('ix_matches_team2'), 'matches', ['team2'], unique=False)
    op.create_index('ix_matches_teams_format', 'matches', ['team1', 'team2', 'match_type'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('batting_style', sa.String(length=64), nullable=True),
    sa.Column('bowling_style', sa.String(length=64), nullable=True),
    sa.Column('role', sa.Enum('BATSMAN', 'BOWLER', 'ALL_ROUNDER', 'WICKETKEEPER', name='playerrole'), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_players')),
    sa.UniqueConstraint('external_id', name=op.f('uq_players_external_id'))
    )
    op.create_index(op.f('ix_players_name'), 'players', ['name'], unique=False)
    op.create_table('batting_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('runs', sa.Integer(), nullable=False),
    sa.Column('balls_faced', sa.Integer(), nullable=True),
    sa.Column('fours', sa.Integer(), nullable=False),
    sa.Column('sixes', sa.Integer(), nullable=False),
    sa.Column('strike_rate', sa.Float(), nullable=True),
    sa.Column('dismissal_type', sa.String(length=32), nullable=True),
    sa.Column('innings_number', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.CheckConstraint('balls_faced IS NULL OR balls_faced >= 0', name=op.f('ck_batting_stats_balls_faced_non_negative')),
    sa.CheckConstraint('innings_number > 0', name=op.f('ck_batting_stats_innings_number_positive')),
    sa.CheckConstraint('runs >= 0', name=op.f('ck_batting_stats_runs_non_negative')),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_batting_stats_match_id_matches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_batting_stats_player_id_players'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batting_stats')),
    sa.UniqueConstraint('match_id', 'player_id', 'innings_number', name='uq_batting_stats_match_player_innings')
    )
    op.create_index(op.f('ix_batting_stats_match_id'), 'batting_stats', ['match_id'], unique=False)
    op.create_index(op.f('ix_batting_stats_player_id'), 'batting_stats', ['player_id'], unique=False)
    op.create_table('bowling_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('overs', sa.Float(), nullable=False),
    sa.Column('maidens', sa.Integer(), nullable=False),
    sa.Column('runs_conceded', sa.Integer(), nullable=False),
    sa.Column('wickets', sa.Integer(), nullable=False),
    sa.Column('economy_rate', sa.Float(), nullable=True),
    sa.Column('extras', sa.Integer(), nullable=True),
    sa.Column('innings_number', sa.Integer(), nullable=False),
    sa.CheckConstraint('innings_number > 0', name=op.f('ck_bowling_stats_innings_number_positive')),
    sa.CheckConstraint('overs >= 0', name=op.f('ck_bowling_stats_overs_non_negative')),
    sa.CheckConstraint('runs_conceded >= 0', name=op.f('ck_bowling_stats_runs_conceded_non_negative')),
    sa.CheckConstraint('wickets >= 0 AND wickets <= 10', name=op.f('ck_bowling_stats_wickets_in_range')),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_bowling_stats_match_id_matches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_bowling_stats_player_id_players'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bowling_stats')),
    sa.UniqueConstraint('match_id', 'player_id', 'innings_number', name='uq_bowling_stats_match_player_innings')
    )
    op.create_index(op.f('ix_bowling_stats_match_id'), 'bowling_stats', ['match_id'], unique=False)
    op.create_index(op.f('ix_bowling_stats_player_id'), 'bowling_stats', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bowling_stats_player_id'), table_name='bowling_stats')
    op.drop_index(op.f('ix_bowling_stats_match_id'), table_name='bowling_stats')
    op.drop_table('bowling_stats')
    op.drop_index(op.f('ix_batting_stats_player_id'), table_name='batting_stats')
    op.drop_index(op.f('ix_batting_stats_match_id'), table_name='batting_stats')
    op.drop_table('batting_stats')
    op.drop_index(op.f('ix_players_name'), table_name='players')
    op.drop_table('players')
    op.drop_index('ix_matches_teams_format', table_name='matches')
    op.drop_index(op.f('ix_matches_team2'), table_name='matches')
    op.drop_index(op.f('ix_matches_team1'), table_name='matches')
    op.drop_index(op.f('ix_matches_match_type'), table_name='matches')
    op.drop_index(op.f('ix_matches_ground'), table_name='matches')
    op.drop_index(op.f('ix_matches_external_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_date'), table_name='matches')
    op.drop_table('matches')
    # ### end Alembic commands ###
